# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adhaar_card',
            field=models.BigIntegerField(default=1, unique=True),
        ),
    ]
