# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_pic', models.ImageField(blank=True, null=True, upload_to='history_pics/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image_title', models.CharField(blank=True, max_length=120, null=True)),
                ('Disease', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
